package com.example.collegearena;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

public class Csesem2Activity extends AppCompatActivity {
    RecyclerView recyclerView;
    List<Credits> creditsList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_csesem2);
        recyclerView=findViewById(R.id.recyclerview);

        initData();
        setRecyclerView();

    }
    private void setRecyclerView() {
        CreditsAdapter creditsAdapter = new CreditsAdapter(creditsList);
        recyclerView.setAdapter(creditsAdapter);
        recyclerView.setHasFixedSize(true);
    }

    private void initData() {
        creditsList = new ArrayList<>();
        creditsList.add(new Credits("BASIC ELECTRICAL ENGINEERING","L:3 T:1 P:2 CREDIT:5", "","MODULE 1: DC CIRCUITS (8 LECTURES)\n" +
                "ELECTRICAL CIRCUIT ELEMENTS (R, L AND C), VOLTAGE AND CURRENT SOURCES," +
                "KIRCHHOFF CURRENT AND VOLTAGE LAWS, ANALYSIS OF SIMPLE CIRCUITS WITH DC" +
                "EXCITATION. STAR-DELTA CONVERSION, NETWORK THEOREMS (SUPERPOSITION, THEVENIN," +
                "NORTON AND MAXIMUM POWER TRANSFER THEOREMS). TIME-DOMAIN ANALYSIS OF FIRSTORDER RL AND RC CIRCUITS\n\n" +
                "MODULE 2: AC CIRCUITS (8 LECTURES)\n" +
                "\t\tREPRESENTATION OF SINUSOIDAL WAVEFORMS, PEAK, RMS AND AVERAGE VALUES (FORM" +
                "FACTOR AND PEAK FACTOR), IMPEDANCE OF SERIES AND PARALLEL CIRCUIT, PHASOR" +
                "REPRESENTATION, REAL POWER, REACTIVE POWER, APPARENT POWER, POWER FACTOR, POWER" +
                "TRIANGLE. ANALYSIS OF SINGLE-PHASE AC CIRCUITS CONSISTING OF R, L, C, RL, RC," +
                "RLC COMBINATIONS (SERIES AND PARALLEL), RESONANCE. THREE-PHASE BALANCED" +
                "CIRCUITS, VOLTAGE AND CURRENT RELATIONS IN STAR AND DELTA CONNECTIONS.\n\n" +
                "MODULE 3: MAGNETIC CIRCUITS: (4 LECTURES)\n" +
                "\t\tINTRODUCTION, SERIES AND PARALLEL MAGNETIC CIRCUITS, ANALYSIS OF SERIES" +
                "AND PARALLEL MAGNETIC CIRCUITS.\n\n" +
                "MODULE 4: TRANSFORMERS (6 LECTURES)\n" +
                "MAGNETIC MATERIALS, BH CHARACTERISTICS, IDEAL AND PRACTICAL TRANSFORMER," +
                "EMF EQUATION, EQUIVALENT CIRCUIT, LOSSES IN TRANSFORMERS, REGULATION AND" +
                "EFFICIENCY. AUTO-TRANSFORMER AND THREE-PHASE TRANSFORMER CONNECTIONS.\n\n" +
                "MODULE 5: ELECTRICAL MACHINES (10 LECTURES)\n" +
                "CONSTRUCTION, WORKING, TORQUE-SPEED CHARACTERISTIC AND SPEED CONTROL OF" +
                "SEPARATELY EXCITED DC MOTOR. GENERATION OF ROTATING MAGNETIC FIELDS," +
                "CONSTRUCTION AND WORKING OF A THREE-PHASE INDUCTION MOTOR, SIGNIFICANCE OF" +
                "TORQUE-SLIP CHARACTERISTIC. LOSS COMPONENTS AND EFFICIENCY, STARTING AND SPEED" +
                "CONTROL OF INDUCTION MOTOR. CONSTRUCTION AND WORKING OF SYNCHRONOUS GENERATORS.\n\n" +
                "MODULE 6: ELECTRICAL INSTALLATIONS (6 LECTURES)\n" +
                "\t\tCOMPONENTS OF LT SWITCHGEAR: SWITCH FUSE UNIT (SFU), MCB, ELCB, MCCB," +
                "TYPES OF WIRES AND CABLES, EARTHING. TYPES OF BATTERIES, IMPORTANT "+
            "CHARACTERISTICS FOR BATTERIES. ELEMENTARY CALCULATIONS FOR ENERGY CONSUMPTION," +
                    "POWER FACTOR IMPROVEMENT AND BATTERY BACKUP.\n\n\n" +
                    "SUGGESTED TEXT / REFERENCE BOOKS\n" +
                    " D. P. KOTHARI AND I. J. NAGRATH, “BASIC ELECTRICAL ENGINEERING”, TATA" +
                    "MCGRAW HILL, 2010.\n" +
                    " D. C. KULSHRESHTHA, “BASIC ELECTRICAL ENGINEERING”, MCGRAW HILL, 2009.\n" +
                    " L. S. BOBROW, “FUNDAMENTALS OF ELECTRICAL ENGINEERING”, OXFORD" +
                    "UNIVERSITY PRESS, 2011.\n" +
                    " E. HUGHES, “ELECTRICAL AND ELECTRONICS TECHNOLOGY”, PEARSON, 2010.\n" +
                    " V. D. TORO, “ELECTRICAL ENGINEERING FUNDAMENTALS”, PRENTICE HALL INDIA," +
                    "1989.\n" +
                    " BASIC ELECTRICAL ENGINEERING BY FITZERALD, ET AL, TATA MCGRAW HILL\n" +
                    " FUNDAMENTALS OF ELECTRICAL ENGG. BY R. PRASAD, PHI PUBLICATION\n" +
                    " BASIC ELECTRICAL ENGINEERING BY V.K. MEHTA AND ROHIT MEHTA, S.CHAND" +
                    "PUBLICATION\n\n\n"));
        creditsList.add(new Credits("ENGINEERING GRAPHICS AND DESIGN", "L:1 T:0 P:4 CREDIT:3","","TRADITIONAL ENGINEERING GRAPHICS:\n" +
                "\t\tPRINCIPLES OF ENGINEERING GRAPHICS; ORTHOGRAPHIC PROJECTION; DESCRIPTIVE" +
                "GEOMETRY; DRAWING PRINCIPLES; ISOMETRIC PROJECTION; SURFACE DEVELOPMENT;" +
                "PERSPECTIVE; READING A DRAWING; SECTIONAL VIEWS; DIMENSIONING & TOLERANCES;" +
                "TRUE LENGTH, ANGLE; INTERSECTION, SHORTEST DISTANCE.\n\n" +
                "COMPUTER GRAPHICS:\n" +
                "\t\tENGINEERING GRAPHICS SOFTWARE; -SPATIAL TRANSFORMATIONS; ORTHOGRAPHIC" +
                "PROJECTIONS; MODEL VIEWING; CO-ORDINATE SYSTEMS; MULTI-VIEW PROJECTION;" +
                "EXPLODED ASSEMBLY; MODEL VIEWING; ANIMATION; SPATIAL MANIPULATION; SURFACE" +
                "MODELLING; SOLID MODELLING, INTRODUCTION TO BUILDING INFORMATION MODELLING" +
                "(BIM).\n\n"+
                "MODULE 1: INTRODUCTION TO ENGINEERING DRAWING\n" +
                "\t\tPRINCIPLES OF ENGINEERING GRAPHICS AND THEIR SIGNIFICANCE, USAGE OF" +
                "DRAWING INSTRUMENTS, LETTERING, CONIC SECTIONS INCLUDING THE RECTANGULAR" +
                "HYPERBOLA (GENERAL METHOD ONLY); CYCLOID, EPICYCLOID, HYPOCYCLOID AND INVOLUTE;" +
                "SCALES – PLAIN, DIAGONAL AND VERNIER SCALES\n\n" +
                "MODULE 2: ORTHOGRAPHIC PROJECTIONS\n" +
                "\t\tPRINCIPLES OF ORTHOGRAPHIC PROJECTIONS-CONVENTIONS -PROJECTIONS OF POINTS" +
                "AND LINES INCLINED TO BOTH PLANES; PROJECTIONS OF PLANES INCLINED PLANES -" +
                "AUXILIARY PLANES\n\n" +
                "MODULE 3: PROJECTIONS OF REGULAR SOLIDS\n" +
                "\t\tTHOSE INCLINED TO BOTH THE PLANES- AUXILIARY VIEWS; DRAW SIMPLE ANNOTATION," +
                "DIMENSIONING AND SCALE. FLOOR PLANS THAT INCLUDE: WINDOWS, DOORS, AND FIXTURES" +
                "SUCH AS WC, BATH, SINK, SHOWER, ETC.\n\n" +
                "MODULE 4: SECTIONS AND SECTIONAL VIEWS OF RIGHT ANGULAR SOLIDS\n" +
                "\t\tCOVERING, PRISM, CYLINDER, PYRAMID, CONE – AUXILIARY VIEWS; DEVELOPMENT" +
                "OF SURFACES OF RIGHT REGULAR SOLIDS- PRISM, PYRAMID, CYLINDER AND CONE; DRAW" +
                "THE SECTIONAL ORTHOGRAPHIC VIEWS OF GEOMETRICAL SOLIDS, OBJECTS FROM INDUSTRY" +
                "AND DWELLINGS (FOUNDATION TO SLAB ONLY)\n\n" +
                "MODULE 5: ISOMETRIC PROJECTIONS.\n"+
                "\t\tPRINCIPLES OF ISOMETRIC PROJECTION – ISOMETRIC SCALE, ISOMETRIC VIEWS," +
                        "CONVENTIONS; ISOMETRIC VIEWS OF LINES, PLANES, SIMPLE AND COMPOUND SOLIDS;" +
                        "CONVERSION OF ISOMETRIC VIEWS TO ORTHOGRAPHIC VIEWS AND VICE-VERSA, CONVENTIONS\n\n" +
                        "MODULE 6: OVERVIEW OF COMPUTER GRAPHICS\n" +
                        "\t\tLISTING THE COMPUTER TECHNOLOGIES THAT IMPACT ON GRAPHICAL COMMUNICATION," +
                        "DEMONSTRATING KNOWLEDGE OF THE THEORY OF CAD SOFTWARE [SUCH AS: THE MENU SYSTEM," +
                        "TOOLBARS (STANDARD, OBJECT PROPERTIES, DRAW, MODIFY AND DIMENSION), DRAWING" +
                        "AREA (BACKGROUND, CROSSHAIRS, COORDINATE SYSTEM), DIALOG BOXES AND WINDOWS," +
                        "SHORTCUT MENUS (BUTTON BARS), THE COMMAND LINE (WHERE APPLICABLE), THE STATUS" +
                        "BAR, DIFFERENT METHODS OF ZOOM AS USED IN CAD, SELECT AND ERASE OBJECTS.;" +
                        "ISOMETRIC VIEWS OF LINES, PLANES, SIMPLE AND COMPOUND SOLIDS]\n\n" +
                        "MODULE 7: CUSTOMISATION& CAD DRAWING\n" +
                        "\t\tCONSISTING OF SET UP OF THE DRAWING PAGE AND THE PRINTER, INCLUDING SCALE" +
                        "SETTINGS, SETTING UP OF UNITS AND DRAWING LIMITS; ISO AND ANSI STANDARDS FOR" +
                        "COORDINATE DIMENSIONING AND TOLERANCING; ORTHOGRAPHIC CONSTRAINTS, SNAP TO" +
                        "OBJECTS MANUALLY AND AUTOMATICALLY; PRODUCING DRAWINGS BY USING VARIOUS" +
                        "COORDINATE INPUT ENTRY METHODS TO DRAW STRAIGHT LINES, APPLYING VARIOUS WAYS OF" +
                        "DRAWING CIRCLES.\n\n" +
                        "MODULE 8: ANNOTATIONS, LAYERING & OTHER FUNCTIONS\n" +
                        "\t\tCOVERING APPLYING DIMENSIONS TO OBJECTS, APPLYING ANNOTATIONS TO" +
                        "DRAWINGS; SETTING UP AND USE OF LAYERS, LAYERS TO CREATE DRAWINGS, CREATE, EDIT" +
                        "AND USE CUSTOMIZED LAYERS; CHANGING LINE LENGTHS THROUGH MODIFYING EXISTING" +
                        "LINES (EXTEND/LENGTHEN); PRINTING DOCUMENTS TO PAPER USING THE PRINT COMMAND;" +
                        "ORTHOGRAPHIC PROJECTION TECHNIQUES; DRAWING SECTIONAL VIEWS OF COMPOSITE RIGHT" +
                        "REGULAR GEOMETRIC SOLIDS AND PROJECT THE TRUE SHAPE OF THE SECTIONED SURFACE;" +
                        "DRAWING ANNOTATION, COMPUTER-AIDED DESIGN (CAD) SOFTWARE MODELING OF PARTS AND" +
                        "ASSEMBLIES. PARAMETRIC AND NON-PARAMETRIC SOLID, SURFACE, AND WIREFRAME MODELS." +
                        "PART EDITING AND TWO-DIMENSIONAL DOCUMENTATION OF MODELS. PLANAR PROJECTION" +
                        "THEORY, INCLUDING SKETCHING OF PERSPECTIVE, ISOMETRIC, MULTIVIEW, AUXILIARY," +
                        "AND SECTION VIEWS. SPATIAL VISUALIZATION EXERCISES. DIMENSIONING GUIDELINES," +
                        "TOLERANCING TECHNIQUES; DIMENSIONING AND SCALE MULTI VIEWS OF DWELLING.\n\n" +
                        "MODULE 9: DEMONSTRATION OF A SIMPLE TEAM DESIGN PROJECT THAT ILLUSTRATES\n" +
                        "\t\tGEOMETRY AND TOPOLOGY OF ENGINEERED COMPONENTS: CREATION OF ENGINEERING" +
                        "MODELS AND THEIR PRESENTATION IN STANDARD 2D BLUEPRINT FORM AND AS 3D WIREFRAME AND SHADED SOLIDS; MESHED TOPOLOGIES FOR ENGINEERING ANALYSIS AND TOOLPATH GENERATION FOR COMPONENT MANUFACTURE; GEOMETRIC DIMENSIONING AND" +
                        "TOLERANCING; USE OF SOLID-MODELING SOFTWARE FOR CREATING ASSOCIATIVE MODELS AT" +
                        "THE COMPONENT AND ASSEMBLY LEVELS. FLOOR PLANS THAT INCLUDE: WINDOWS, DOORS," +
                        "AND FIXTURES SUCH AS WC, BATH, SINK, SHOWER, ETC. APPLYING COLOUR CODING"+
                "ACCORDING TO BUILDING DRAWING PRACTICE; DRAWING SECTIONAL ELEVATION SHOWING" +
                "FOUNDATION TO CEILING; INTRODUCTION TO BUILDING INFORMATION MODELLING (BIM).\n\n\n" +
                "SUGGESTED TEXT/REFERENCE BOOKS:\n" +
                " BHATT N.D., PANCHAL V.M. & INGLE P.R., (2014), ENGINEERING DRAWING," +
                "CHAROTAR PUBLISHING HOUSE\n" +
                " SHAH, M.B. &RANA B.C. (2008), ENGINEERING DRAWING AND COMPUTER GRAPHICS," +
                "PEARSON EDUCATION\n" +
                " AGRAWAL B. & AGRAWAL C. M. (2012), ENGINEERING GRAPHICS, TMH PUBLICATION" +
                " NARAYANA, K.L. & P KANNAIAH (2008), TEXT BOOK ON ENGINEERING DRAWING," +
                "SCITECHPUBLISHERS\n" +
                " (CORRESPONDING SET OF) CAD SOFTWARE THEORY AND USER MANUALS\n\n\n"));
        creditsList.add(new Credits("MATHEMATICS - II (PROBABILITY AND STATISTICS)","L:3 T:1 P:0 CREDIT:4","","MODULE 1: BASIC PROBABILITY (12 LECTURES).\n" +
                "\t\tPROBABILITY SPACES, CONDITIONAL PROBABILITY, INDEPENDENCE; DISCRETE" +
                "RANDOM VARIABLES, INDEPENDENT RANDOM VARIABLES, THE MULTINOMIAL DISTRIBUTION," +
                "POISSON APPROXIMATION TO THE BINOMIAL DISTRIBUTION, INFINITE SEQUENCES OF" +
                "BERNOULLI TRIALS, SUMS OF INDEPENDENT RANDOM VARIABLES; EXPECTATION OF DISCRETE" +
                "RANDOM VARIABLES, MOMENTS, VARIANCE OF A SUM, CORRELATION COEFFICIENT," +
                "CHEBYSHEV'S INEQUALITY.\n\n" +
                "MODULE 2: CONTINUOUS PROBABILITY DISTRIBUTIONS (4 LECTURES)\n" +
                "CONTINUOUS RANDOM VARIABLES AND THEIR PROPERTIES, DISTRIBUTION FUNCTIONS" +
                "AND DENSITIES, NORMAL, EXPONENTIAL AND GAMMA DENSITIES.\n\n" +
                "MODULE 3: BIVARIATE DISTRIBUTIONS (4 LECTURES)\n" +
                "BIVARIATE DISTRIBUTIONS AND THEIR PROPERTIES, DISTRIBUTION OF SUMS AND" +
                "QUOTIENTS, CONDITIONAL DENSITIES, BAYES' RULE.\n\n" +
                "MODULE 4: BASIC STATISTICS (8 LECTURES)\n" +
                "MEASURES OF CENTRAL TENDENCY: MOMENTS, SKEWNESS AND KURTOSIS - PROBABILITY" +
                "DISTRIBUTIONS: BINOMIAL, POISSON AND NORMAL - EVALUATION OF STATISTICAL" +
                "PARAMETERS FOR THESE THREE DISTRIBUTIONS, CORRELATION AND REGRESSION – RANK" +
                "CORRELATION.\n\n" +
                "MODULE 5: APPLIED STATISTICS (8 LECTURES)\n" +
                "CURVE FITTING BY THE METHOD OF LEAST SQUARES- FITTING OF STRAIGHT LINES," +
                "SECOND DEGREE PARABOLAS AND MORE GENERAL CURVES. TEST OF SIGNIFICANCE: LARGE" +
                "SAMPLE TEST FOR SINGLE PROPORTION,DIFFERENCE OF PROPORTIONS, SINGLE MEAN," +
                "DIFFERENCE OF MEANS AND DIFFERENCE OF STANDARD DEVIATIONS.\n\n" +
                "MODULE 6: SMALL SAMPLES (4 LECTURES)\n" +
                "TEST FOR SINGLE MEAN, DIFFERENCE OF MEANS AND CORRELATION COEFFICIENTS," +
                "TEST FOR RATIO OF VARIANCES - CHI-SQUARE TEST FOR GOODNESS OF FIT AND" +
                "INDEPENDENCE OF ATTRIBUTES.\n\n" +
                "TEXT / REFERENCES:\n" +
                " E. KREYSZIG, “ADVANCED ENGINEERING MATHEMATICS”, JOHN WILEY & SONS, 2006.\n"+
        "P. G. HOEL, S. C. PORT AND C. J. STONE, “INTRODUCTION TO PROBABILITY" +
                "THEORY”, UNIVERSAL BOOK STALL, 2003.\n" +
                " S. ROSS, “A FIRST COURSE IN PROBABILITY”, PEARSON EDUCATION INDIA, 2002.\n" +
                " W. FELLER, “AN INTRODUCTION TO PROBABILITY THEORY AND ITS APPLICATIONS”," +
                "VOL. 1, WILEY, 1968.\n" +
                " N.P. BALI AND M. GOYAL, “A TEXT BOOK OF ENGINEERING MATHEMATICS”, LAXMI" +
                "PUBLICATIONS, 2010.\n" +
                " B.S. GREWAL, “HIGHER ENGINEERING MATHEMATICS”, KHANNA PUBLISHERS, 2000." +
                " T. VEERARAJAN, “ENGINEERING MATHEMATICS”, TATA MCGRAW-HILL, NEW DELHI," +
                "2010"));
        creditsList.add(new Credits("PHYSICS (SEMICONDUCTOR PHYSICS)","L:3 T:1 P:3 CREDIT:5.5","","MODULE 1: REVIEW OF SEMICONDUCTOR PHYSICS (10 LECTURES)\n" +
                "E-K DIAGRAM, DENSITY OF STATES, OCCUPATION PROBABILITY, FERMI LEVEL AND" +
                "QUASI-FERMI LEVEL (VARIATION BY CARRIER CONCENTRATION AND TEMPERATURE); P-N" +
                "JUNCTION, METAL-SEMICONDUCTOR JUNCTION (OHMIC AND SCHOTTKY); CARRIER" +
                "TRANSPORT, GENERATION, AND RECOMBINATION; SEMICONDUCTOR MATERIALS OF" +
                "INTEREST FOR OPTOELECTRONIC DEVICES, BANDGAP MODIFICATION, HETEROSTRUCTURES;" +
                "LIGHT- SEMICONDUCTOR INTERACTION: RATES OF OPTICAL TRANSITIONS, JOINT" +
                "DENSITY OF STATES, CONDITION FOR OPTICAL AMPLIFICATION.\n\n" +
                "MODULE 2: SEMICONDUCTOR LIGHT EMITTING DIODES (LEDS) (6 LECTURES).\n" +
                "RATE EQUATIONS FOR CARRIER DENSITY, RADIATIVE AND NON-RADIATIVE" +
                "RECOMBINATION MECHANISMS IN SEMICONDUCTORS, LED: DEVICE STRUCTURE, MATERIALS," +
                "CHARACTERISTICS, AND FIGURES OF MERIT.\n\n" +
                "MODULE 3: SEMICONDUCTOR LASERS (8 LECTURES).\n" +
                "REVIEW OF LASER PHYSICS; RATE EQUATIONS FOR CARRIER- AND PHOTON-DENSITY," +
                "AND THEIR STEADY STATE SOLUTIONS, LASER DYNAMICS, RELAXATION OSCILLATIONS," +
                "INPUT-OUTPUT CHARACTERISTICS OF LASERS. SEMICONDUCTOR LASER: STRUCTURE," +
                "MATERIALS, DEVICE CHARACTERISTICS, AND FIGURES OF MERIT; DFB, DBR, AND VERTICALCAVITY SURFACE-EMITTING LASERS (VECSEL), TUNABLE SEMICONDUCTOR LASERS.\n\n" +
                "MODULE 4: PHOTODETECTORS (6 LECTURES)\n" +
                "TYPES OF SEMICONDUCTOR PHOTODETECTORS -P-N JUNCTION, PIN, AND AVALANCHE" +
                "AND THEIR STRUCTURE, MATERIALS, WORKING PRINCIPLE, AND CHARACTERISTICS, NOISE" +
                "LIMITS ON PERFORMANCE; SOLAR CELLS.\n\n" +
                "MODULE 5: LOW-DIMENSIONAL OPTOELECTRONIC DEVICES (6 LECTURES)\n" +
                "QUANTUM-WELL, -WIRE, AND -DOT BASED LEDS, LASERS, AND PHOTODETECTORS.\n\n\n" +
                "SUGGESTED TEXT/REFERENCE BOOKS\n" +
                " J. SINGH, SEMICONDUCTOR OPTOELECTRONICS: PHYSICS AND TECHNOLOGY, MCGRAWHILL INC. (1995).\n" +
                " B. E. A. SALEH AND M. C. TEICH, FUNDAMENTALS OF PHOTONICS, JOHN WILEY &" +
                "SONS,"));
    }
}