package com.example.collegearena;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

public class Ecesem1sylActivity extends AppCompatActivity {
    RecyclerView recyclerView;
    List<Credits> creditsList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ecesem1syl);
        recyclerView = findViewById(R.id.recyclerview);

        initData();
        setRecyclerView();
    }

    private void setRecyclerView() {
        CreditsAdapter creditsAdapter = new CreditsAdapter(creditsList);
        recyclerView.setAdapter(creditsAdapter);
        recyclerView.setHasFixedSize(true);
    }

    private void initData() {
        creditsList = new ArrayList<>();
        creditsList.add(new Credits("CHEMISTRY", "L:3 T:1 P:3 CREDIT 5.5","", "MODULE 1: ATOMIC AND MOLECULAR STRUCTURE (10 LECTURES)\n\n" +
                "\t\tFAILURE OF CLASSICAL NEWTONIAN AND MAXWELL WAVE MECHANICS TO EXPLAIN, " +
                "PROPERTIES OF PARTICLES AT ATOMIC AND SUB-ATOMIC LEVEL; ELECTROMAGNETIC, " +
                "RADIATION, DUAL NATURE OF ELECTRON AND ELECTROMAGNETIC RADIATION, PLANK’S THEORY, " +
                "PHOTOELECTRIC EFFECT AND HEISENBERG UNCERTAINTY PRINCIPLE. FAILURE OF EARLIER, " +
                "THEORIES TO EXPLAIN CERTAIN PROPERTIES OF MOLECULES LIKE PARAMAGNETIC PROPERTIES," +
                "PRINCIPLES FOR COMBINATION OF ATOMIC ORBITALS TO FORM MOLECULAR ORBITALS, " +
                "FORMATION OF HOMO AND HETERO DIATOMIC MOLECULES AND PLOTS OF ENERGY LEVEL," +
                "DIAGRAM OF MOLECULAR ORBITALS. COORDINATION NUMBERS AND GEOMETRIES, ISOMERISM, " +
                "IN TRANSITIONAL METAL COMPOUNDS, CRYSTAL FIELD THEORY AND THE ENERGY LEVEL," +
                "DIAGRAMS FOR TRANSITION METAL IONS AND THEIR MAGNETIC PROPERTIES.\n\n" +
                "MODULE 2: SPECTROSCOPIC TECHNIQUES AND APPLICATIONS (8 LECTURES)\n\n" +
                "\t\tPRINCIPLES OF VIBRATIONAL AND ROTATIONAL SPECTROSCOPY AND SELECTION RULES," +
                "FOR APPLICATION IN DIATOMIC MOLECULES. ELEMENTARY IDEA OF ELECTRONIC," +
                "SPECTROSCOPY. UV-VIS SPECTROSCOPY WITH RELATED RULES AND ITS APPLICATIONS," +
                "FLUORESCENCE AND ITS APPLICATIONS IN MEDICINE. BASIC PRINCIPLE OF NUCLEAR," +
                "MAGNETIC RESONANCE AND ITS APPLICATION. BASICS OF MAGNETIC RESONANCE IMAGING.\n\n" +
                "MODULE 3: INTERMOLECULAR FORCES AND PROPERTIES OF GASES (4 LECTURES)\n\n" +
                "\t\tIONIC, DIPOLAR AND VAN DER WAALS INTERACTIONS, EQUATIONS OF STATE OF IDEAL," +
                "AND REAL GASES, DEVIATION FROM IDEAL BEHAVIOUR. VANDER WAAL GAS EQUATION.\n\n" +
                "MODULE 4: USE OF FREE ENERGY IN CHEMICAL EQUILIBRIA & WATER CHEMISTRY, " +
                "\t\tTHERMODYNAMIC FUNCTIONS: ENERGY, ENTHALPY ENTROPY AND FREE ENERGY, " +
                "EQUATIONS TO INTERRELATE THERMODYNAMIC PROPERTIES. FREE ENERGY, EMF. AND CELL," +
                "POTENTIALS, THE NERNST EQUATION AND APPLICATIONS. CORROSION. USE OF FREE ENERGY," +
                "CONSIDERATIONS IN METALLURGY THROUGH ELLINGHAM DIAGRAMS. SOLUBILITY EQUILIBRIA," +
                "WATER CHEMISTRY, HARD AND SOFT WATER. PARAMETERS OF QUALITY OF WATER TO," +
                "BE USED IN DIFFERENT INDUSTRIES AS FOR DRINKING WATER. CALCULATION OF HARDNESS," +
                "OF WATER IN ALL UNITS. ESTIMATION OF HARDNESS USING EDTA AND ALKALINITY METHOD," +
                "REMOVAL OF HARDNESS BY SODA LIME AND ION EXCHANGE METHOD INCLUDING ZEOLITE METHOD\n\n" +
                "MODULE 5: PERIODIC PROPERTIES (4 LECTURES).\n" +
                "\t\tEFFECTIVE NUCLEAR CHARGE, PENETRATION OF ORBITALS, VARIATIONS OF S, P, DAND F ORBITAL ENERGIES OF ATOMS IN THE PERIODIC TABLE, ELECTRONIC CONFIGURATIONS," +
                "ATOMIC AND IONIC SIZES, IONIZATION ENERGIES, ELECTRON AFFINITY AND ELECTRONEGATIVITY, " +
                "POLARIZABILITY, ACID, BASE, PRINCIPLE OF HSAB THEORY," +
                "OXIDATION STATES, HYBRIDIZATION AND MOLECULAR GEOMETRIES.\n\n" +
                "MODULE 6: STEREOCHEMISTRY (4 LECTURES).\n" +
                "\t\tREPRESENTATIONS OF 3-D STRUCTURES, STRUCTURAL ISOMERS & STEREOISOMERS, " +
                "CONFIGURATIONS AND SYMMETRY AND CHIRALITY, ENANTIOMERS, DIASTEREOMERS, OPTICAL" +
                "ACTIVITY, ABSOLUTE CONFIGURATIONS AND CONFORMATIONAL ANALYSIS.\n\n" +
                "MODULE 7: ORGANIC REACTIONS AND SYNTHESIS OF A DRUG MOLECULE (4 LECTURES).\n" +
                "\t\tINTRODUCTION TO INTERMEDIATES AND REACTIONS INVOLVING SUBSTITUTION," +
                "ADDITION, ELIMINATION, OXIDATION- REDUCTION, DIELS ELDER CYCLIZATION AND" +
                "EPOXIDE RING OPENINGS REACTIONS. SYNTHESIS OF A COMMONLY USED DRUG MOLECULE" +
                "LIKE ASPIRIN.\n\n\n" +
                "SUGGESTED TEXT BOOKS\n" +
                "\t\t\tUNIVERSITY CHEMISTRY, BY B. H. MAHAN\n" +
                "CHEMISTRY: PRINCIPLES AND APPLICATIONS, BY M. J. SIENKO AND R. A. PLANE\n" +
                " FUNDAMENTALS OF MOLECULAR SPECTROSCOPY, BY C. N. BANWELL\n" +
                " ENGINEERING CHEMISTRY (NPTEL WEB-BOOK), BY B. L. TEMBE, KAMALUDDIN AND M." +
                "S. KRISHNAN\n" +
                " PHYSICAL CHEMISTRY, BY P. W. ATKINS\n" +
                "ORGANIC CHEMISTRY: STRUCTURE AND FUNCTION BY K. P. C. VOLHARDT AND N. E." +
                "SCHORE, 5TH EDITION\n\n\n" ));
        creditsList.add(new Credits("MATHEMATICS -I (CALCULUS & DIFFERENTIAL EQUATIONS)","L:3 T:1 P:0 CREDIT:4","","MODULE 1: CALCULUS (8 LECTURES).\n" +
                "\t\tEVOLUTES AND INVOLUTES; EVALUATION OF DEFINITE AND IMPROPER INTEGRALS;" +
                "BETA AND GAMMA FUNCTIONS AND THEIR PROPERTIES; APPLICATIONS OF DEFINITE" +
                "INTEGRALS TO EVALUATE SURFACE AREAS AND VOLUMES OF REVOLUTIONS. ROLLE’S THEOREM," +
                "MEAN VALUE THEOREMS, TAYLOR’S AND MACLAURIN THEOREMS WITH REMAINDERS;" +
                "INDETERMINATE FORMS AND L'HOSPITAL'S RULE; MAXIMA AND MINIMA." +
                "MODULE 2: SEQUENCES AND SERIES (7 LECTURES).\n" +
                "\t\tCONVERGENCE OF SEQUENCE AND SERIES, TESTS FOR CONVERGENCE, POWER SERIES," +
                "TAYLOR'S SERIES. SERIES FOR EXPONENTIAL, TRIGONOMETRIC AND LOGARITHMIC" +
                "FUNCTIONS; FOURIER SERIES: HALF RANGE SINE AND COSINE SERIES, PARSEVAL’S THEOREM.\n\n" +
                "MODULE 3: MULTIVARIABLE CALCULUS: DIFFERENTIATION (6 LECTURES).\n" +
                "\t\tLIMIT, CONTINUITY AND PARTIAL DERIVATIVES, DIRECTIONAL DERIVATIVES, TOTAL" +
                "DERIVATIVE; TANGENT PLANE AND NORMAL LINE; MAXIMA, MINIMA AND SADDLE POINTS;" +
                "METHOD OF LAGRANGE MULTIPLIERS; GRADIENT, CURL AND DIVERGENCE.\n\n" +
                "MODULE 4: MULTIVARIABLE CALCULUS: INTEGRATION (7 LECTURES)\n" +
                "\t\tMULTIPLE INTEGRATION: DOUBLE AND TRIPLE INTEGRALS (CARTESIAN AND POLAR)," +
                "CHANGE OF ORDER OF INTEGRATION IN DOUBLE INTEGRALS, CHANGE OF VARIABLES" +
                "(CARTESIAN TO POLAR), APPLICATIONS: AREAS AND VOLUMES BY (DOUBLE INTEGRATION)" +
                "CENTER OF MASS AND GRAVITY (CONSTANT AND VARIABLE DENSITIES). THEOREMS OF GREEN," +
                "GAUSS AND STOKES, ORTHOGONAL CURVILINEAR COORDINATES, SIMPLE APPLICATIONS" +
                "INVOLVING CUBES, SPHERE AND RECTANGULAR PARALLELEPIPEDS.\n\n" +
                "MODULE 5: FIRST ORDER ORDINARY DIFFERENTIAL EQUATIONS (3 LECTURES)\n" +
                "\t\tEXACT, LINEAR AND BERNOULLI’S EQUATIONS, EULER’S EQUATIONS, EQUATIONS NOT" +
                "OF FIRST DEGREE: EQUATIONS SOLVABLE FOR P, EQUATIONS SOLVABLE FOR Y, EQUATIONS" +
                "SOLVABLE FOR X AND CLAIRAUT’S TYPE.\n\n" +
                "MODULE 6: ORDINARY DIFFERENTIAL EQUATIONS OF HIGHER ORDER (6 LECTURES)\n" +
                "\t\tSECOND ORDER LINEAR DIFFERENTIAL EQUATIONS WITH VARIABLE COEFFICIENTS," +
                "METHOD OF VARIATION OF PARAMETERS, CAUCHY-EULER EQUATION; POWER SERIES" +
                "SOLUTIONS; LEGENDRE POLYNOMIALS, BESSEL FUNCTIONS OF THE FIRST KIND AND THEIR" +
                "PROPERTIES.\n\n" +
                "MODULE 7: PARTIAL DIFFERENTIAL EQUATIONS: FIRST ORDER (3 LECTURES)\n" +
                "FIRST ORDER PARTIAL DIFFERENTIAL EQUATIONS, SOLUTIONS OF FIRST ORDER" +
                "LINEAR AND NON-LINEAR PDES." +
                "TEXT / REFERENCES:\n" +
                " \t\t\tG.B. THOMAS AND R.L. FINNEY, “CALCULUS AND ANALYTIC GEOMETRY”, PEARSON," +
                "2002.\n" +
                " T. VEERARAJAN, “ENGINEERING MATHEMATICS”, MCGRAW-HILL, NEW DELHI, 2008.\n" +
                " B. V. RAMANA, “HIGHER ENGINEERING MATHEMATICS”, MCGRAW HILL, NEW DELHI," +
                "2010.\n" +
                " N.P. BALI AND M. GOYAL, “A TEXT BOOK OF ENGINEERING MATHEMATICS”, LAXMI" +
                "PUBLICATIONS, 2010.\n" +
                " B.S. GREWAL, “HIGHER ENGINEERING MATHEMATICS”, KHANNA PUBLISHERS, 2000.\n" +
                " E. KREYSZIG, “ADVANCED ENGINEERING MATHEMATICS”, JOHN WILEY & SONS, 2006.\n" +
                " W. E. BOYCE AND R. C. DIPRIMA, “ELEMENTARY DIFFERENTIAL EQUATIONS AND" +
                "BOUNDARY VALUE PROBLEMS”, WILEY INDIA, 2009.\n" +
                " S. L. ROSS, “DIFFERENTIAL EQUATIONS”, WILEY INDIA, 1984.\n" +
                " E. A. CODDINGTON, “AN INTRODUCTION TO ORDINARY DIFFERENTIAL EQUATIONS”," +
                "PRENTICE HALL INDIA, 1995.\n" +
                " E. L. INCE, “ORDINARY DIFFERENTIAL EQUATIONS”, DOVER PUBLICATIONS, 1958.\n" +
                " G.F. SIMMONS AND S.G. KRANTZ, “DIFFERENTIAL EQUATIONS”, MCGRAW HILL, 2007."));
        creditsList.add(new Credits("PPS (PROGRAMMING FOR PROBLEM SOLVING)","L:3 T:0 P:4 CREDIT:5","","MODULE 1: INTRODUCTION TO PROGRAMMING (6 LECTURES).\n" +
                "\tINTRODUCTION TO COMPONENTS OF A COMPUTER SYSTEM (DISKS, MEMORY, PROCESSOR," +
                "WHERE A PROGRAM IS STORED AND EXECUTED, OPERATING SYSTEM, COMPILERS ETC). IDEA" +
                "OF ALGORITHM: STEPS TO SOLVE LOGICAL AND NUMERICAL PROBLEMS. REPRESENTATION OF" +
                "ALGORITHM: FLOWCHART/PSEUDO CODE WITH EXAMPLES. FROM ALGORITHMS TO PROGRAMS;" +
                "SOURCE CODE, VARIABLES (WITH DATA TYPES) VARIABLES AND MEMORY LOCATIONS, TYPE" +
                "CASTING/TYPE CONVERSION, RUN TIME ENVIRONMENT (STATIC, DYNAMIC LOCATION)," +
                "STORAGE CLASSES (AUTO, REGISTER, STATIC, EXTERN), SYNTAX AND LOGICAL ERRORS IN" +
                "COMPILATION, OBJECT AND EXECUTABLE CODE.\n\n" +
                "MODULE 2: OPERATORS (3 LECTURES)\n" +
                "\tARITHMETIC EXPRESSIONS/ARITHMETIC OPERATORS/RELATIONAL OPERATORS/LOGICAL" +
                "OPERATORS/BITWISE OPERATORS AND PRECEDENCE\n\n" +
                "MODULE 3: CONDITIONAL BRANCHING AND LOOPS (5 LECTURES).\n" +
                "\tWRITING AND EVALUATION OF CONDITIONALS AND CONSEQUENT BRANCHING," +
                "ITERATION AND LOOPS.\n\n" +
                "MODULE 4: ARRAYS (4 LECTURES).\n" +
                "\tARRAY DECLARATION & INITIALIZATION, BOUND CHECKING ARRAYS (1-D, 2-D)," +
                "CHARACTER ARRAYS AND STRINGS.\n\n" +
                "MODULE 5: BASIC ALGORITHMS (6 LECTURES).\n" +
                "\tSEARCHING (LINEAR SEARCH, BINARY SEARCH ETC.), BASIC SORTING ALGORITHMS" +
                "(BUBBLE, INSERTION AND SELECTION), FINDING ROOTS OF EQUATIONS, NOTION OF ORDER" +
                "OF COMPLEXITY THROUGH EXAMPLE PROGRAMS (NO FORMAL DEFINITION REQUIRED)\n\n" +
                "MODULE 6: FUNCTION (4 LECTURES).\n" +
                "\tINTRODUCTION & WRITING FUNCTIONS, SCOPE OF VARIABLES FUNCTIONS (INCLUDING" +
                "USING BUILT IN LIBRARIES), PARAMETER PASSING IN FUNCTIONS, CALL BY VALUE," +
                "PASSING ARRAYS TO FUNCTIONS: IDEA OF CALL BY REFERENCE\n\n" +
                "MODULE 7: RECURSION (5 LECTURES).\n" +
                "\tRECURSION, AS A DIFFERENT WAY OF SOLVING PROBLEMS. EXAMPLE PROGRAMS, SUCH" +
                "AS FINDING FACTORIAL, FIBONACCI SERIES, REVERSE A STRING USING RECURSION, AND" +
                "GCD OF TWO NUMBERS, ACKERMAN FUNCTION ETC. QUICK SORT OR MERGE SORT.\n\n" +
                "MODULE 8: STRUCTURE/UNION (3 LECTURES).\n" +
                "\tSTRUCTURES, ACCESSING STRUCTURE ELEMENTS, WAY OF STORAGE OF STRUCTURE" +
                "ELEMENT, DEFINING STRUCTURES AND ARRAY OF STRUCTURES, BASIC DEFINITION OF UNION," +
                "COMPARISON B/W STRUCTURE & UNION WITH EXAMPLE\n\n" +
                "MODULE 9: POINTERS (5 LECTURES).\n" +
                "\tIDEA OF POINTERS, DEFINING POINTERS, USE OF POINTERS IN SELF-REFERENTIAL" +
                "STRUCTURES, NOTION OF LINKED LIST (NO IMPLEMENTATION), POINTER TO POINTER," +
                "POINTER TO ARRAY, POINTER TO STRINGS, ARRAY OF POINTER, POINTER TO FUNCTION," +
                "POINTER TO STRUCTURE.\n\n" +
                "MODULE 10: FILE HANDLING\n" +
                "(ONLY IF TIME IS AVAILABLE, OTHERWISE SHOULD BE DONE AS PART OF THE LAB)\n\n\n" +
                "SUGGESTED TEXT BOOKS\n" +
                " \t\t\tBYRON GOTTFRIED, SCHAUM'S OUTLINE OF PROGRAMMING WITH C, MCGRAW-HILL\n" +
                " E. BALAGURUSWAMY, PROGRAMMING IN ANSI C, TATA MCGRAW-HILL\n" +
                "SUGGESTED REFERENCE BOOKS\n" +
                " BRIAN W. KERNIGHAN AND DENNIS M. RITCHIE, THE C PROGRAMMING LANGUAGE,\n" +
                "PRENTICE HALL OF INDIA" +
                " YASHWANT KANETKAR, LET US C, BPB PUBLICATION\n\n\n"));
        creditsList.add(new Credits("WORKSHOP MANUFACTURING PRACTICES","L:1 T:0 P:4 CREDIT:3","","DETAILED CONTENTS:\n" +
                "1. MANUFACTURING METHODS-CASTING, FORMING, MACHINING, JOINING, ADVANCED" +
                "MANUFACTURING METHODS (3 LECTURES)\n" +
                "2. CNC MACHINING, ADDITIVE MANUFACTURING (1 LECTURE)\n" +
                "3. FITTING OPERATIONS & POWER TOOLS (1 LECTURE)\n" +
                "4. CARPENTRY (1 LECTURE)\n" +
                "5. PLASTIC MOULDING, GLASS CUTTING (1 LECTURE)\n" +
                "6. METAL CASTING (1 LECTURE)\n" +
                "7. WELDING (ARC WELDING & GAS WELDING), BRAZING, SOLDERING (2 LECTURE)\n\n\n" +
                "SUGGESTED TEXT/REFERENCE BOOKS:\n" +
                " \t\t\tHAJRA CHOUDHURY S.K., HAJRA CHOUDHURY A.K. AND NIRJHAR ROY S.K., “ELEMENTS" +
                "OF WORKSHOP TECHNOLOGY”, VOL. I 2008 AND VOL. II 2010, MEDIA PROMOTERS" +
                "AND PUBLISHERS PRIVATE LIMITED, MUMBAI.\n" +
                " KALPAKJIAN S. AND STEVEN S. SCHMID, “MANUFACTURING ENGINEERING AND" +
                "TECHNOLOGY”, 4TH EDITION, PEARSON EDUCATION INDIA EDITION, 2002.\n" +
                " GOWRI P. HARIHARAN AND A. SURESH BABU,”MANUFACTURING TECHNOLOGY – I”" +
                "PEARSON EDUCATION, 2008.\n" +
                " ROY A. LINDBERG, “PROCESSES AND MATERIALS OF MANUFACTURE”, 4TH EDITION," +
                "PRENTICE HALL INDIA, 1998.\n" +
                " RAO P.N., “MANUFACTURING TECHNOLOGY”, VOL. I AND VOL. II, TATA MCGRAWHILL" +
                "HOUSE, 2017\n\n\n"));
        creditsList.add(new Credits("ENGLISH","L:2 T:0 P:2 CREDIT:3","","1. VOCABULARY BUILDING\n" +
                "\t\tA. THE CONCEPT OF WORD FORMATION\n" +
                "B. ROOT WORDS FROM FOREIGN LANGUAGES AND THEIR USE IN ENGLISH\n" +
                "C. ACQUAINTANCE WITH PREFIXES AND SUFFIXES FROM FOREIGN LANGUAGES IN" +
                "ENGLISH TO FORM DERIVATIVES.\n" +
                "D. SYNONYMS, ANTONYMS, AND STANDARD ABBREVIATIONS.\n" +
                "E. AFFIXES, ACRONYMS\n\n" +
                "2. BASIC WRITING SKILLS\n" +
                "A. \t\tSENTENCE STRUCTURES\n" +
                "B. USE OF PHRASES AND CLAUSES IN SENTENCES\n" +
                "C. IMPORTANCE OF PROPER PUNCTUATION\n" +
                "D. KINDS OF SENTENCES\n" +
                "E. USE OF TENSE, USE IN CONTEXT AND COHERENCE OF TENSE IN WRITING\n" +
                "F. USE OF VOICE – ACTIVE/PASSIVE IN SENTENCES\n" +
                "G. USE OF SPEECH – DIRECT AND INDIRECT SPEECH\n" +
                "H. FRAMING QUESTIONS- DIRECT, USING MODAL VERBS\n\n" +
                "3. IDENTIFYING COMMON ERRORS IN WRITING\n" +
                "A. \t\tSUBJECT-VERB AGREEMENT\n" +
                "B. NOUN-PRONOUN AGREEMENT\n" +
                "C. MISPLACED MODIFIERS\n" +
                "D. ARTICLES\n" +
                "E. PREPOSITIONS\n" +
                "F. REDUNDANCIES\n" +
                "G. CLICHÉS\n" +
                "H. COMMON ENGLISH ERRORS\n\n" +
                "4. NATURE AND STYLE OF SENSIBLE WRITING\n" +
                "A. DESCRIBING\n" +
                "B. DEFINING\n" +
                "C. CLASSIFYING\n" +
                "D. PROVIDING EXAMPLES OR EVIDENCE\n" +
                "E. WRITING INTRODUCTION AND CONCLUSION\n" +
                "F. ORGANISING PRINCIPLE OF PARAGRAPHS IN DOCUMENTS\n" +
                "G. ARGUMENT, DESCRIBING/ NARRATING/ PLANNING, DEFINING,CLASSIFYING\n" +
                "H. LEXICAL RESOURCES, USING SUITABLE LANGUAGE REGISTER\n" +
                "I. COHERENCE, WRITING INTRODUCTION, BODY AND CONCLUSION, TECHNIQUES FOR" +
                "WRITING PRECISELY,GRAMMAR AND ACCURACY\n\n" +
                "5. WRITING PRACTICES\n" +
                "A. COMPREHENSION\n" +
                "B. FORMAL LETTER WRITING/ APPLICATION/ REPORT WRITING/ WRITING MINUTES OF" +
                "MEETINGS\n" +
                "C. ESSAY WRITING\n" +
                "D. FORMAL EMAIL WRITING\n" +
                "E. RESUME/ CV WRITING, COVER LETTER,\n" +
                "F. STATEMENT OF PURPOSE\n\n" +
                "6. ORAL COMMUNICATION\n" +
                "(THIS UNIT INVOLVES INTERACTIVE PRACTICE SESSIONS IN LANGUAGE LAB)\n" +
                "A. LISTENING COMPREHENSION\n" +
                "B. PRONUNCIATION, INTONATION, STRESS AND RHYTHM\n" +
                "C. COMMON EVERYDAY SITUATIONS: CONVERSATIONS AND DIALOGUES\n" +
                "D. COMMUNICATION AT WORKPLACE\n" +
                "E. INTERVIEWS\n" +
                "F. FORMAL PRESENTATIONS\n" +
                "G. ACQUAINTING STUDENTS WITH IPA SYMBOLS\n" +
                "H. PHONETICS (BASIC)\n" +
                "I. SOUNDS – VOWELS, CONSONANTS\n" +
                "J. CLEARING MOTHER TONGUE INFLUENCE\n" +
                "K. CLEARING REDUNDANCIES AND COMMON ERRORS RELATED TO INDIANISMS\n" +
                "L. GROUP DISCUSSION\n" +
                "M. EXPRESSING OPINIONS\n" +
                "N. COHERENCE AND FLUENCY IN SPEECH\n\n" +
                "7. READING SKILLS\n" +
                "A. READING COMPREHENSION,\n" +
                "B. PARAGRAPH READING BASED ON PHONETIC SOUNDS/ INTONATION\n\n" +
                "8. PROFESSIONAL SKILLS\n" +
                "A. TEAM BUILDING\n" +
                "B. SOFT SKILLS AND ETIQUETTES\n\n" +
                "9. ACQUAINTANCE WITH TECHNOLOGY-AIDED LANGUAGE LEARNING\n" +
                "A. USE OF COMPUTER SOFTWARE (GRAMMARLY, GINGER…)\n" +
                "B. USE OF SMARTPHONE APPLICATIONS (DUOLINGO, BUSUU…)\n\n" +
                "10. ACTIVITIES\n" +
                "A. NARRATIVE CHAIN\n" +
                "B. DESCRIBING/ NARRATING\n" +
                "C. WRITING ESSAYS IN RELAY\n" +
                "D. PEER/ GROUP ACTIVITIES\n" +
                "E. BRAINSTORMING VOCABULARY\n" +
                "F. CUE / FLASH CARDS FOR VOCABULARY\n" +
                "G. DEBATES\n\n\n" +
                "SUGGESTED READINGS:\n" +
                " \t\t\tPRACTICAL ENGLISH USAGE. MICHAEL SWAN. OUP. 1995.\n" +
                " REMEDIAL ENGLISH GRAMMAR. F.T. WOOD. MACMILLAN.2007\n" +
                " ON WRITING WELL. WILLIAM ZINSSER. HARPER RESOURCE BOOK. 2001\n" +
                " STUDY WRITING. LIZ HAMP-LYONS AND BEN HEASLY. CAMBRIDGE UNIVERSITY" +
                "PRESS. 2006.\n" +
                " COMMUNICATION SKILLS. SANJAY KUMAR AND PUSHPLATA. OXFORD UNIVERSITY" +
                "PRESS. 2011.\n" +
                " EXERCISES IN SPOKEN ENGLISH. PARTS. I-III. CIEFL, HYDERABAD. OXFORD" +
                "UNIVERSITY PRESS\n\n\n"));

    }

}
