package com.example.collegearena;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;

import java.util.ArrayList;
import java.util.List;

public class Ecesem2sylActivity extends AppCompatActivity {
    RecyclerView recyclerView;
    List<Credits> creditsList;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_ecesem2syl);
        recyclerView = findViewById(R.id.recyclerview);

        initData();
        setRecyclerView();
    }
    private void setRecyclerView() {
        CreditsAdapter creditsAdapter = new CreditsAdapter(creditsList);
        recyclerView.setAdapter(creditsAdapter);
        recyclerView.setHasFixedSize(true);
    }

    private void initData() {
        creditsList = new ArrayList<>();
        creditsList.add(new Credits("Physics (Waves and Optics, and Introduction to Quantum Mechanics)", "L:3 T:0 P:4 Credits:5", "", "MODULE 1: WAVES (3 LECTURES)" +
                "MECHANICAL AND ELECTRICAL SIMPLE HARMONIC OSCILLATORS, DAMPED HARMONIC" +
                "OSCILLATOR, FORCED MECHANICAL AND ELECTRICAL OSCILLATORS, IMPEDANCE, STEADY" +
                "STATE MOTION OF FORCED DAMPED HARMONIC OSCILLATOR" +
                "MODULE 2: NON-DISPERSIVE TRANSVERSE AND LONGITUDINAL WAVES (4 LECTURES)" +
                "TRANSVERSE WAVE ON A STRING, THE WAVE EQUATION ON A STRING, HARMONIC" +
                "WAVES, REFLECTION AND TRANSMISSION OF WAVES AT A BOUNDARY, IMPEDANCE MATCHING," +
                "STANDING WAVES AND THEIR EIGEN FREQUENCIES, LONGITUDINAL WAVES AND THE WAVE" +
                "EQUATION FOR THEM, ACOUSTICS WAVES" +
                "MODULE 3: LIGHT AND OPTICS (3 LECTURES)" +
                "LIGHT AS AN ELECTROMAGNETIC WAVE AND FRESNEL EQUATIONS, REFLECTANCE AND" +
                "TRANSMITTANCE, BREWSTER’S ANGLE, TOTAL INTERNAL REFLECTION, AND EVANESCENT WAVE." +
                "MIRRORS AND LENSES AND OPTICAL INSTRUMENTS BASED ON THEM" +
                "MODULE 4: WAVE OPTICS (5 LECTURES)" +
                "HUYGENS’ PRINCIPLE, SUPERPOSITION OF WAVES AND INTERFERENCE OF LIGHT BY" +
                "WAVEFRONT SPLITTING AND AMPLITUDE SPLITTING; YOUNG’S DOUBLE SLIT EXPERIMENT," +
                "NEWTON’S RINGS, MICHELSON INTERFEROMETER, MACH ZEHNDER INTERFEROMETER." +
                "FARUNHOFER DIFFRACTION FROM A SINGLE SLIT AND A CIRCULAR APERTURE, THE RAYLEIGH" +
                "CRITERION FOR LIMIT OF RESOLUTION AND ITS APPLICATION TO VISION; DIFFRACTION" +
                "GRATINGS AND THEIR RESOLVING POWER" +
                "MODULE 5: LASERS (5 LECTURES)" +
                "EINSTEIN’S THEORY OF MATTER RADIATION INTERACTION AND A AND B" +
                "COEFFICIENTS; AMPLIFICATION OF LIGHT BY POPULATION INVERSION, DIFFERENT TYPES" +
                "OF LASERS: GAS LASERS (HE-NE, CO2), SOLID-STATE LASERS (RUBY, NEODYMIUM), DYE" +
                "LASERS; PROPERTIES OF LASER BEAMS: MONO-CHROMATICITY" +
                "MODULE 6: INTRODUCTION TO QUANTUM MECHANICS (5 LECTURES)" +
                "WAVE NATURE OF PARTICLES, TIME-DEPENDENT AND TIME-INDEPENDENT SCHRODINGER" +
                "EQUATION FOR WAVE FUNCTION, BORN INTERPRETATION, PROBABILITY CURRENT," +
                "EXPECTATION VALUES, FREE-PARTICLE WAVE FUNCTION AND WAVE-PACKETS, UNCERTAINTY" +
                "PRINCIPLE." +
                "[AKU-PATNA] [103 –EE || 110 – EEE || 104 – ECE]" +
                "27 | P a g e B A C K" +
                "MODULE 7: SOLUTION OF WAVE EQUATION (6 LECTURES)" +
                "SOLUTION OF STATIONARY-STATE SCHRODINGER EQUATION FOR ONE DIMENSIONAL" +
                "PROBLEMS–PARTICLE IN A BOX, PARTICLE IN ATTRACTIVE DELTA-FUNCTION POTENTIAL," +
                "SQUARE-WELL POTENTIAL, LINEAR HARMONIC OSCILLATOR. SCATTERING FROM A POTENTIAL" +
                "BARRIER AND TUNNELING; RELATED EXAMPLES LIKE ALPHA- DECAY, FIELD-IONIZATION AND" +
                "SCANNING TUNNELING MICROSCOPE, TUNNELING IN SEMICONDUCTOR STRUCTURES. THREEDIMENSIONAL PROBLEMS: PARTICLE IN THREE DIMENSIONAL BOX AND RELATED EXAMPLES." +
                "MODULE 8: INTRODUCTION TO SOLIDS AND SEMICONDUCTORS (9 LECTURES)" +
                "FREE ELECTRON THEORY OF METALS, FERMI LEVEL, DENSITY OF STATES IN 1, 2" +
                "AND 3 DIMENSIONS, BLOCH’S THEOREM FOR PARTICLES IN A PERIODIC POTENTIAL, KRONIGPENNEY MODEL AND ORIGIN OF ENERGY BANDS." +
                "TYPES OF ELECTRONIC MATERIALS: METALS, SEMICONDUCTORS, AND INSULATORS." +
                "INTRINSIC AND EXTRINSIC SEMICONDUCTORS, DEPENDENCE OF FERMI LEVEL ON CARRIERCONCENTRATION AND TEMPERATURE (EQUILIBRIUM CARRIER STATISTICS), CARRIER" +
                "GENERATION AND RECOMBINATION, CARRIER TRANSPORT: DIFFUSION AND DRIFT, P -N" +
                "JUNCTION." +
                "TEXT / REFERENCES:" +
                " G. MAIN, “VIBRATIONS AND WAVES IN PHYSICS”, CAMBRIDGE UNIVERSITY PRESS," +
                "1993." +
                " H. J. PAIN, “THE PHYSICS OF VIBRATIONS AND WAVES”, WILEY, 2006." +
                " E. HECHT, “OPTICS”, PEARSON EDUCATION, 2008." +
                " A. GHATAK, “OPTICS”, MCGRAW HILL EDUCATION, 2012." +
                " O. SVELTO, “PRINCIPLES OF LASERS”, SPRINGER SCIENCE & BUSINESS MEDIA," +
                "2010." +
                " D. J. GRIFFITHS, “QUANTUM MECHANICS”, PEARSON EDUCATION, 2014." +
                " R. ROBINETT, “QUANTUM MECHANICS”, OUP OXFORD, 2006." +
                " D. MCQUARRIE, “UANTUM CHEMISTRY”, UNIVERSITY SCIENCE BOOKS, 2007." +
                " D. A. NEAMEN, “SEMICONDUCTOR PHYSICS AND DEVICES”, TIMES MIRROR HIGH" +
                "EDUCATION GROUP, CHICAGO, 1997." +
                " E.S. YANG, “MICROELECTRONIC DEVICES”, MCGRAW HILL, SINGAPORE, 1988." +
                " B.G. STREETMAN, “ SOLID STATE ELECTRONIC DEVICES”, PRENTICE HALL OF INDIA," +
                "1995"));
        creditsList.add(new Credits("Mathematics –II (Linear Algebra, Transform Calculus and Numerical Methods)", "L:3 T:0 P:4 Credits:5", "", ""));
        creditsList.add(new Credits("BASIC ELECTRICAL ENGINEERING","L:3 T:1 P:2 CREDIT:5", "","MODULE 1: DC CIRCUITS (8 LECTURES)\n\n" +
                "ELECTRICAL CIRCUIT ELEMENTS (R, L AND C), VOLTAGE AND CURRENT SOURCES," +
                "KIRCHHOFF CURRENT AND VOLTAGE LAWS, ANALYSIS OF SIMPLE CIRCUITS WITH DC" +
                "EXCITATION. STAR-DELTA CONVERSION, NETWORK THEOREMS (SUPERPOSITION, THEVENIN," +
                "NORTON AND MAXIMUM POWER TRANSFER THEOREMS). TIME-DOMAIN ANALYSIS OF FIRSTORDER RL AND RC CIRCUITS" +
                "MODULE 2: AC CIRCUITS (8 LECTURES)" +
                "\t\tREPRESENTATION OF SINUSOIDAL WAVEFORMS, PEAK, RMS AND AVERAGE VALUES (FORM" +
                "FACTOR AND PEAK FACTOR), IMPEDANCE OF SERIES AND PARALLEL CIRCUIT, PHASOR" +
                "REPRESENTATION, REAL POWER, REACTIVE POWER, APPARENT POWER, POWER FACTOR, POWER" +
                "TRIANGLE. ANALYSIS OF SINGLE-PHASE AC CIRCUITS CONSISTING OF R, L, C, RL, RC," +
                "RLC COMBINATIONS (SERIES AND PARALLEL), RESONANCE. THREE-PHASE BALANCED" +
                "CIRCUITS, VOLTAGE AND CURRENT RELATIONS IN STAR AND DELTA CONNECTIONS." +
                "MODULE 3: MAGNETIC CIRCUITS: (4 LECTURES)" +
                "\t\tINTRODUCTION, SERIES AND PARALLEL MAGNETIC CIRCUITS, ANALYSIS OF SERIES" +
                "AND PARALLEL MAGNETIC CIRCUITS." +
                "MODULE 4: TRANSFORMERS (6 LECTURES)\n\n" +
                "MAGNETIC MATERIALS, BH CHARACTERISTICS, IDEAL AND PRACTICAL TRANSFORMER," +
                "EMF EQUATION, EQUIVALENT CIRCUIT, LOSSES IN TRANSFORMERS, REGULATION AND" +
                "EFFICIENCY. AUTO-TRANSFORMER AND THREE-PHASE TRANSFORMER CONNECTIONS." +
                "MODULE 5: ELECTRICAL MACHINES (10 LECTURES)" +
                "CONSTRUCTION, WORKING, TORQUE-SPEED CHARACTERISTIC AND SPEED CONTROL OF" +
                "SEPARATELY EXCITED DC MOTOR. GENERATION OF ROTATING MAGNETIC FIELDS," +
                "CONSTRUCTION AND WORKING OF A THREE-PHASE INDUCTION MOTOR, SIGNIFICANCE OF" +
                "TORQUE-SLIP CHARACTERISTIC. LOSS COMPONENTS AND EFFICIENCY, STARTING AND SPEED" +
                "CONTROL OF INDUCTION MOTOR. CONSTRUCTION AND WORKING OF SYNCHRONOUS GENERATORS." +
                "MODULE 6: ELECTRICAL INSTALLATIONS (6 LECTURES)" +
                "\t\tCOMPONENTS OF LT SWITCHGEAR: SWITCH FUSE UNIT (SFU), MCB, ELCB, MCCB," +
                "TYPES OF WIRES AND CABLES, EARTHING. TYPES OF BATTERIES, IMPORTANT "+
                "CHARACTERISTICS FOR BATTERIES. ELEMENTARY CALCULATIONS FOR ENERGY CONSUMPTION," +
                "POWER FACTOR IMPROVEMENT AND BATTERY BACKUP." +
                "SUGGESTED TEXT / REFERENCE BOOKS" +
                " D. P. KOTHARI AND I. J. NAGRATH, “BASIC ELECTRICAL ENGINEERING”, TATA" +
                "MCGRAW HILL, 2010." +
                " D. C. KULSHRESHTHA, “BASIC ELECTRICAL ENGINEERING”, MCGRAW HILL, 2009." +
                " L. S. BOBROW, “FUNDAMENTALS OF ELECTRICAL ENGINEERING”, OXFORD" +
                "UNIVERSITY PRESS, 2011." +
                " E. HUGHES, “ELECTRICAL AND ELECTRONICS TECHNOLOGY”, PEARSON, 2010." +
                " V. D. TORO, “ELECTRICAL ENGINEERING FUNDAMENTALS”, PRENTICE HALL INDIA," +
                "1989." +
                " BASIC ELECTRICAL ENGINEERING BY FITZERALD, ET AL, TATA MCGRAW HILL" +
                " FUNDAMENTALS OF ELECTRICAL ENGG. BY R. PRASAD, PHI PUBLICATION" +
                " BASIC ELECTRICAL ENGINEERING BY V.K. MEHTA AND ROHIT MEHTA, S.CHAND" +
                "PUBLICATION"));
        creditsList.add(new Credits("ENGINEERING GRAPHICS AND DESIGN", "L:1 T:0 P:4 CREDIT:3","","TRADITIONAL ENGINEERING GRAPHICS:" +
                "\t\tPRINCIPLES OF ENGINEERING GRAPHICS; ORTHOGRAPHIC PROJECTION; DESCRIPTIVE" +
                "GEOMETRY; DRAWING PRINCIPLES; ISOMETRIC PROJECTION; SURFACE DEVELOPMENT;" +
                "PERSPECTIVE; READING A DRAWING; SECTIONAL VIEWS; DIMENSIONING & TOLERANCES;" +
                "TRUE LENGTH, ANGLE; INTERSECTION, SHORTEST DISTANCE." +
                "COMPUTER GRAPHICS:" +
                "\t\tENGINEERING GRAPHICS SOFTWARE; -SPATIAL TRANSFORMATIONS; ORTHOGRAPHIC" +
                "PROJECTIONS; MODEL VIEWING; CO-ORDINATE SYSTEMS; MULTI-VIEW PROJECTION;" +
                "EXPLODED ASSEMBLY; MODEL VIEWING; ANIMATION; SPATIAL MANIPULATION; SURFACE" +
                "MODELLING; SOLID MODELLING, INTRODUCTION TO BUILDING INFORMATION MODELLING" +
                "(BIM)."+
                "MODULE 1: INTRODUCTION TO ENGINEERING DRAWING" +
                "\t\tPRINCIPLES OF ENGINEERING GRAPHICS AND THEIR SIGNIFICANCE, USAGE OF" +
                "DRAWING INSTRUMENTS, LETTERING, CONIC SECTIONS INCLUDING THE RECTANGULAR" +
                "HYPERBOLA (GENERAL METHOD ONLY); CYCLOID, EPICYCLOID, HYPOCYCLOID AND INVOLUTE;" +
                "SCALES – PLAIN, DIAGONAL AND VERNIER SCALES" +
                "MODULE 2: ORTHOGRAPHIC PROJECTIONS" +
                "\t\tPRINCIPLES OF ORTHOGRAPHIC PROJECTIONS-CONVENTIONS -PROJECTIONS OF POINTS" +
                "AND LINES INCLINED TO BOTH PLANES; PROJECTIONS OF PLANES INCLINED PLANES -" +
                "AUXILIARY PLANES" +
                "MODULE 3: PROJECTIONS OF REGULAR SOLIDS" +
                "\t\tTHOSE INCLINED TO BOTH THE PLANES- AUXILIARY VIEWS; DRAW SIMPLE ANNOTATION," +
                "DIMENSIONING AND SCALE. FLOOR PLANS THAT INCLUDE: WINDOWS, DOORS, AND FIXTURES" +
                "SUCH AS WC, BATH, SINK, SHOWER, ETC." +
                "MODULE 4: SECTIONS AND SECTIONAL VIEWS OF RIGHT ANGULAR SOLIDS" +
                "\t\tCOVERING, PRISM, CYLINDER, PYRAMID, CONE – AUXILIARY VIEWS; DEVELOPMENT" +
                "OF SURFACES OF RIGHT REGULAR SOLIDS- PRISM, PYRAMID, CYLINDER AND CONE; DRAW" +
                "THE SECTIONAL ORTHOGRAPHIC VIEWS OF GEOMETRICAL SOLIDS, OBJECTS FROM INDUSTRY" +
                "AND DWELLINGS (FOUNDATION TO SLAB ONLY)" +
                "MODULE 5: ISOMETRIC PROJECTIONS."+
                "\t\tPRINCIPLES OF ISOMETRIC PROJECTION – ISOMETRIC SCALE, ISOMETRIC VIEWS," +
                "CONVENTIONS; ISOMETRIC VIEWS OF LINES, PLANES, SIMPLE AND COMPOUND SOLIDS;" +
                "CONVERSION OF ISOMETRIC VIEWS TO ORTHOGRAPHIC VIEWS AND VICE-VERSA, CONVENTIONS" +
                "MODULE 6: OVERVIEW OF COMPUTER GRAPHICS" +
                "\t\tLISTING THE COMPUTER TECHNOLOGIES THAT IMPACT ON GRAPHICAL COMMUNICATION," +
                "DEMONSTRATING KNOWLEDGE OF THE THEORY OF CAD SOFTWARE [SUCH AS: THE MENU SYSTEM," +
                "TOOLBARS (STANDARD, OBJECT PROPERTIES, DRAW, MODIFY AND DIMENSION), DRAWING" +
                "AREA (BACKGROUND, CROSSHAIRS, COORDINATE SYSTEM), DIALOG BOXES AND WINDOWS," +
                "SHORTCUT MENUS (BUTTON BARS), THE COMMAND LINE (WHERE APPLICABLE), THE STATUS" +
                "BAR, DIFFERENT METHODS OF ZOOM AS USED IN CAD, SELECT AND ERASE OBJECTS.;" +
                "ISOMETRIC VIEWS OF LINES, PLANES, SIMPLE AND COMPOUND SOLIDS]" +
                "MODULE 7: CUSTOMISATION& CAD DRAWING" +
                "\t\tCONSISTING OF SET UP OF THE DRAWING PAGE AND THE PRINTER, INCLUDING SCALE" +
                "SETTINGS, SETTING UP OF UNITS AND DRAWING LIMITS; ISO AND ANSI STANDARDS FOR" +
                "COORDINATE DIMENSIONING AND TOLERANCING; ORTHOGRAPHIC CONSTRAINTS, SNAP TO" +
                "OBJECTS MANUALLY AND AUTOMATICALLY; PRODUCING DRAWINGS BY USING VARIOUS" +
                "COORDINATE INPUT ENTRY METHODS TO DRAW STRAIGHT LINES, APPLYING VARIOUS WAYS OF" +
                "DRAWING CIRCLES." +
                "MODULE 8: ANNOTATIONS, LAYERING & OTHER FUNCTIONS" +
                "\t\tCOVERING APPLYING DIMENSIONS TO OBJECTS, APPLYING ANNOTATIONS TO" +
                "DRAWINGS; SETTING UP AND USE OF LAYERS, LAYERS TO CREATE DRAWINGS, CREATE, EDIT" +
                "AND USE CUSTOMIZED LAYERS; CHANGING LINE LENGTHS THROUGH MODIFYING EXISTING" +
                "LINES (EXTEND/LENGTHEN); PRINTING DOCUMENTS TO PAPER USING THE PRINT COMMAND;" +
                "ORTHOGRAPHIC PROJECTION TECHNIQUES; DRAWING SECTIONAL VIEWS OF COMPOSITE RIGHT" +
                "REGULAR GEOMETRIC SOLIDS AND PROJECT THE TRUE SHAPE OF THE SECTIONED SURFACE;" +
                "DRAWING ANNOTATION, COMPUTER-AIDED DESIGN (CAD) SOFTWARE MODELING OF PARTS AND" +
                "ASSEMBLIES. PARAMETRIC AND NON-PARAMETRIC SOLID, SURFACE, AND WIREFRAME MODELS." +
                "PART EDITING AND TWO-DIMENSIONAL DOCUMENTATION OF MODELS. PLANAR PROJECTION" +
                "THEORY, INCLUDING SKETCHING OF PERSPECTIVE, ISOMETRIC, MULTIVIEW, AUXILIARY," +
                "AND SECTION VIEWS. SPATIAL VISUALIZATION EXERCISES. DIMENSIONING GUIDELINES," +
                "TOLERANCING TECHNIQUES; DIMENSIONING AND SCALE MULTI VIEWS OF DWELLING." +
                "MODULE 9: DEMONSTRATION OF A SIMPLE TEAM DESIGN PROJECT THAT ILLUSTRATES" +
                "\t\tGEOMETRY AND TOPOLOGY OF ENGINEERED COMPONENTS: CREATION OF ENGINEERING" +
                "MODELS AND THEIR PRESENTATION IN STANDARD 2D BLUEPRINT FORM AND AS 3D WIREFRAME AND SHADED SOLIDS; MESHED TOPOLOGIES FOR ENGINEERING ANALYSIS AND TOOLPATH GENERATION FOR COMPONENT MANUFACTURE; GEOMETRIC DIMENSIONING AND" +
                "TOLERANCING; USE OF SOLID-MODELING SOFTWARE FOR CREATING ASSOCIATIVE MODELS AT" +
                "THE COMPONENT AND ASSEMBLY LEVELS. FLOOR PLANS THAT INCLUDE: WINDOWS, DOORS," +
                "AND FIXTURES SUCH AS WC, BATH, SINK, SHOWER, ETC. APPLYING COLOUR CODING"+
                "ACCORDING TO BUILDING DRAWING PRACTICE; DRAWING SECTIONAL ELEVATION SHOWING" +
                "FOUNDATION TO CEILING; INTRODUCTION TO BUILDING INFORMATION MODELLING (BIM)." +
                "SUGGESTED TEXT/REFERENCE BOOKS:" +
                " BHATT N.D., PANCHAL V.M. & INGLE P.R., (2014), ENGINEERING DRAWING," +
                "CHAROTAR PUBLISHING HOUSE" +
                " SHAH, M.B. &RANA B.C. (2008), ENGINEERING DRAWING AND COMPUTER GRAPHICS," +
                "PEARSON EDUCATION" +
                " AGRAWAL B. & AGRAWAL C. M. (2012), ENGINEERING GRAPHICS, TMH PUBLICATION" +
                " NARAYANA, K.L. & P KANNAIAH (2008), TEXT BOOK ON ENGINEERING DRAWING," +
                "SCITECHPUBLISHERS" +
                " (CORRESPONDING SET OF) CAD SOFTWARE THEORY AND USER MANUALS"));
    }
}